version = 5.5.0
archive_dir = /etc/letsencrypt/archive/api.rukshanict.lk
cert = /etc/letsencrypt/live/api.rukshanict.lk/cert.pem
privkey = /etc/letsencrypt/live/api.rukshanict.lk/privkey.pem
chain = /etc/letsencrypt/live/api.rukshanict.lk/chain.pem
fullchain = /etc/letsencrypt/live/api.rukshanict.lk/fullchain.pem
[renewalparams]
account = 062723f7963d080621b665d6e4bc48f1
authenticator = webroot
webroot_path = /var/www/certbot,
server = https://acme-v02.api.letsencrypt.org/directory
key_type = ecdsa
[[webroot_map]]
api.rukshanict.lk = /var/www/certbot
